// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddOrUpdateDataBaseInfo(arg1, arg2) {
  return window['go']['main']['App']['AddOrUpdateDataBaseInfo'](arg1, arg2);
}

export function AddPath(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddPath'](arg1, arg2, arg3);
}

export function BrowserOpenURL(arg1) {
  return window['go']['main']['App']['BrowserOpenURL'](arg1);
}

export function DeleteOneDataBaseInfo(arg1) {
  return window['go']['main']['App']['DeleteOneDataBaseInfo'](arg1);
}

export function DeleteZk(arg1) {
  return window['go']['main']['App']['DeleteZk'](arg1);
}

export function GetAllDataBaseInfo() {
  return window['go']['main']['App']['GetAllDataBaseInfo']();
}

export function GetCodeGroup() {
  return window['go']['main']['App']['GetCodeGroup']();
}

export function GetCommand() {
  return window['go']['main']['App']['GetCommand']();
}

export function GetCopyData() {
  return window['go']['main']['App']['GetCopyData']();
}

export function GetCopyHis() {
  return window['go']['main']['App']['GetCopyHis']();
}

export function GetFileCache(arg1) {
  return window['go']['main']['App']['GetFileCache'](arg1);
}

export function GetItemList() {
  return window['go']['main']['App']['GetItemList']();
}

export function GetKafkaForm() {
  return window['go']['main']['App']['GetKafkaForm']();
}

export function GetLanguageList() {
  return window['go']['main']['App']['GetLanguageList']();
}

export function GetOnlineToolsList() {
  return window['go']['main']['App']['GetOnlineToolsList']();
}

export function GetOrDefaultAllSettings() {
  return window['go']['main']['App']['GetOrDefaultAllSettings']();
}

export function GetTopicAndPartition() {
  return window['go']['main']['App']['GetTopicAndPartition']();
}

export function InitZk() {
  return window['go']['main']['App']['InitZk']();
}

export function JsonToXml(arg1) {
  return window['go']['main']['App']['JsonToXml'](arg1);
}

export function ReadZkNode(arg1) {
  return window['go']['main']['App']['ReadZkNode'](arg1);
}

export function SetForm(arg1) {
  return window['go']['main']['App']['SetForm'](arg1);
}

export function UpdateFileCache(arg1, arg2) {
  return window['go']['main']['App']['UpdateFileCache'](arg1, arg2);
}

export function UpdateKafkaForm(arg1) {
  return window['go']['main']['App']['UpdateKafkaForm'](arg1);
}

export function UpdateSystemSettings(arg1) {
  return window['go']['main']['App']['UpdateSystemSettings'](arg1);
}
