// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPath(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddPath'](arg1, arg2, arg3);
}

export function BrowserOpenURL(arg1) {
  return window['go']['main']['App']['BrowserOpenURL'](arg1);
}

export function DeleteZk(arg1) {
  return window['go']['main']['App']['DeleteZk'](arg1);
}

export function GetCommand() {
  return window['go']['main']['App']['GetCommand']();
}

export function GetCopyData() {
  return window['go']['main']['App']['GetCopyData']();
}

export function GetCopyHis() {
  return window['go']['main']['App']['GetCopyHis']();
}

export function GetItemList() {
  return window['go']['main']['App']['GetItemList']();
}

export function GetKafkaForm() {
  return window['go']['main']['App']['GetKafkaForm']();
}

export function GetLanguageList() {
  return window['go']['main']['App']['GetLanguageList']();
}

export function GetNowLanguage() {
  return window['go']['main']['App']['GetNowLanguage']();
}

export function GetOnlineToolsList() {
  return window['go']['main']['App']['GetOnlineToolsList']();
}

export function GetTopicAndPartition() {
  return window['go']['main']['App']['GetTopicAndPartition']();
}

export function InitZk() {
  return window['go']['main']['App']['InitZk']();
}

export function JsonToXml(arg1) {
  return window['go']['main']['App']['JsonToXml'](arg1);
}

export function ReadZkNode(arg1) {
  return window['go']['main']['App']['ReadZkNode'](arg1);
}

export function SetForm(arg1) {
  return window['go']['main']['App']['SetForm'](arg1);
}

export function SetNowLanguage(arg1) {
  return window['go']['main']['App']['SetNowLanguage'](arg1);
}

export function UpdateKafkaForm(arg1) {
  return window['go']['main']['App']['UpdateKafkaForm'](arg1);
}
